---
kind: pipeline
type: docker
name: helloworld

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/heads/main

steps:
- name: helloworld
  image: ubuntu
  commands:
  - "echo ${DRONE_COMMIT_SHA:0:8}"
  - "echo v${DRONE_TAG##*v}"
  - "echo helloworld"

---
kind: pipeline
type: docker
name: build-tag

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/tags/rocr-v**
  - refs/tags/amdgpu-v**

steps:
- name: helloworld
  image: ubuntu
  commands:
  - "echo ${DRONE_COMMIT_SHA:0:8}"
  - "echo v${DRONE_TAG##*v}"

- name: publish-rocr
  image: plugins/docker
  settings:
    repo: kayuii/rocr
    tags:
    - latest
    - v${DRONE_TAG##*v}
    dockerfile: rocm-opencl-runtime/Dockerfile-ubuntu-20.04
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - ROCM_VERSION=${DRONE_TAG##*v}
  when:
    ref:
    - refs/tags/rocr-v**

- name: publish-rocm-opencl-runtime
  image: plugins/docker
  settings:
    repo: kayuii/rocm-opencl-runtime
    tags:
    - latest
    - 20.04
    - v${DRONE_TAG##*v}
    dockerfile: rocm-opencl-runtime/Dockerfile-ubuntu-20.04
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - ROCM_VERSION=${DRONE_TAG##*v}
  when:
    ref:
    - refs/tags/rocr-v**

- name: publish-amdgpu
  image: plugins/docker
  settings:
    repo: kayuii/amdgpu
    tags:
    - latest
    - v${DRONE_TAG##*v}
    dockerfile: amdgpu/Dockerfile-ubuntu-20.04
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - AMDGPU_VERSION=${DRONE_TAG##*v}
  when:
    ref:
    - refs/tags/amdgpu-v**

...
